# generated by Neptune Namespaces v3.x.x
# file: Score/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:        require './App'       
  Main:       require './Main'      
  Palette:    require './Palette'   
  StyleProps: require './StyleProps'
require './Components'
require './Models'
require './Pipelines'