# generated by Neptune Namespaces v2.x.x
# file: Score/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:        require './App'       
  Main:       require './Main'      
  StyleProps: require './StyleProps'
require './Components'
require './Models'