# generated by Neptune Namespaces v2.x.x
# file: Score/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Score ||
Neptune.addNamespace 'Score', class Score extends Neptune.Base
  ;
require './Components/namespace';
require './Models/namespace'