# generated by Neptune Namespaces v3.x.x
# file: Score/.JustScore/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:  require './App' 
  Main: require './Main'
require './Components'
require './Models'