# generated by Neptune Namespaces v3.x.x
# file: Score/.JustScore/namespace.coffee

module.exports = (require '../namespace').addNamespace('JustScore', class JustScore extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace'