# generated by Neptune Namespaces v3.x.x
# file: Score/Components/Pages/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Game:      require './Game'     
  Games:     require './Games'    
  GameTypes: require './GameTypes'
  NewGame:   require './NewGame'  
  Page:      require './Page'     
  Players:   require './Players'  