# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreMore/Components/Partials/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PlayerList: require './PlayerList'