# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreMore/namespace.coffee

module.exports = (require '../namespace').addNamespace('ScoreMore', class ScoreMore extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace';
require './Pipelines/namespace'