# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreKeeper/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Main:           require './Main'          
  StandardImport: require './StandardImport'
  Style:          require './Style'         
require './Components'
require './Models'