# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreKeeper/namespace.coffee

module.exports = (require '../namespace').addNamespace('ScoreKeeper', class ScoreKeeper extends Neptune.PackageNamespace)
require './Components/namespace';
require './Models/namespace'