# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreKeeper/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:           require './App'          
  Button:        require './Button'       
  ColorPicker:   require './ColorPicker'  
  ConfirmDelete: require './ConfirmDelete'
  History:       require './History'      
  Keyboard:      require './Keyboard'     
  Label:         require './Label'        
  PlayerEditor:  require './PlayerEditor' 
  PlayerScore2:  require './PlayerScore2' 
  ScoreView:     require './ScoreView'    