# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreKeeper/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  App:           require './App'          
  Button:        require './Button'       
  ColorPicker:   require './ColorPicker'  
  ConfirmDelete: require './ConfirmDelete'
  Keyboard:      require './Keyboard'     
  Label:         require './Label'        
  PlayerEditor:  require './PlayerEditor' 
require './Pages'
require './Partials'