# generated by Neptune Namespaces v3.x.x
# file: Score/Components/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Button:  require './Button' 
  TextBox: require './TextBox'