# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreKeeper/Components/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ButtonWrapper: require './ButtonWrapper'