# generated by Neptune Namespaces v3.x.x
# file: Score/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  PlayerLine: require './PlayerLine'
  PlayerList: require './PlayerList'
require './Pages'
require './Partials'
require './Widgets'