# generated by Neptune Namespaces v3.x.x
# file: Score/Components/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  MainScreen: require './MainScreen'
  PlayerLine: require './PlayerLine'
  PlayerList: require './PlayerList'