# generated by Neptune Namespaces v2.x.x
# file: Score/Components/namespace.coffee

Score = require '../namespace'
module.exports = Score.Components ||
Score.addNamespace 'Components', class Components extends Neptune.Base
  ;
