# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreMore/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  IndexedDbPipeline: require './IndexedDbPipeline'
  NavState:          require './NavState'         
  NewGameState:      require './NewGameState'     
  Players:           require './Players'          