# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreKeeper/Components/Pages/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CurrentGame:    require './CurrentGame'   
  GameHistory:    require './GameHistory'   
  Games:          require './Games'         
  StandardImport: require './StandardImport'