# generated by Neptune Namespaces v3.x.x
# file: Score/Widgets/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Button:        require './Button'       
  ButtonWrapper: require './ButtonWrapper'
  TextBox:       require './TextBox'      