# generated by Neptune Namespaces v3.x.x
# file: Score/.JustScore/Models/namespace.coffee

module.exports = (require '../namespace').addNamespace('Models', class Models extends Neptune.PackageNamespace)
