# generated by Neptune Namespaces v3.x.x
# file: Score/.ScoreMore/Pipelines/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Game:         require './Game'        
  GamePlayer:   require './GamePlayer'  
  GameType:     require './GameType'    
  Player:       require './Player'      
  ScoreHistory: require './ScoreHistory'