# generated by Neptune Namespaces v3.x.x
# file: Score/Models/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  IndexedDbPipeline: require './IndexedDbPipeline'
  Players:           require './Players'          