# generated by Neptune Namespaces v2.x.x
# file: Score/Models/namespace.coffee

Score = require '../namespace'
module.exports = Score.Models ||
Score.addNamespace 'Models', class Models extends Neptune.Base
  ;
